# Generated by Django 4.2.7 on 2025-06-18 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dessuser',
            name='assigned_solutions',
        ),
        migrations.CreateModel(
            name='UserSolutionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si la asignación está activa')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la asignación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.solution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Solución',
                'verbose_name_plural': 'Asignaciones de Soluciones',
                'db_table': 'dess_user_solution_assignments',
                'unique_together': {('user', 'solution')},
            },
        ),
        migrations.AddField(
            model_name='dessuser',
            name='assigned_solutions',
            field=models.ManyToManyField(blank=True, help_text='Soluciones asignadas al usuario', through='database.UserSolutionAssignment', to='database.solution'),
        ),
    ]
