# Generated by Django 4.2 on 2025-07-21 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó la solución', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_solutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_type',
            field=models.CharField(choices=[('web_app', 'Aplicación Web'), ('desktop_app', 'Aplicación de Escritorio'), ('mobile_app', 'Aplicación Móvil'), ('api', 'API/Servicio Web'), ('database', 'Base de Datos'), ('other', 'Otro')], default='web_app', help_text='Tipo de aplicación', max_length=20),
        ),
    ]
