# Generated by Django 5.2.3 on 2025-06-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_dessuser_assigned_solutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessuser',
            name='assigned_solutions',
            field=models.ManyToManyField(blank=True, help_text='Soluciones asignadas al usuario', through='database.UserSolutionAssignment', through_fields=('user', 'solution'), to='database.solution'),
        ),
    ]
