# Generated by Django 5.2.4 on 2025-09-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('database', '0002_solution_created_by_alter_solution_solution_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dessuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='dessuser',
            name='assigned_solutions',
            field=models.ManyToManyField(blank=True, help_text='Soluciones asignadas al usuario', through='database.UserSolutionAssignment', through_fields=('user', 'solution'), to='database.solution'),
        ),
        migrations.AddIndex(
            model_name='dessuser',
            index=models.Index(fields=['role'], name='idx_user_role'),
        ),
        migrations.AddIndex(
            model_name='dessuser',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='dessuser',
            index=models.Index(fields=['username', 'role'], name='idx_user_username_role'),
        ),
        migrations.AddIndex(
            model_name='dessuser',
            index=models.Index(fields=['is_active'], name='idx_user_is_active'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['status'], name='idx_solution_status'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['solution_type'], name='idx_solution_type'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['created_by'], name='idx_solution_created_by'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['-created_at'], name='idx_solution_created_at'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['name', 'status'], name='idx_solution_name_status'),
        ),
        migrations.AddIndex(
            model_name='usersolutionaccess',
            index=models.Index(fields=['user', '-accessed_at'], name='idx_access_user_time'),
        ),
        migrations.AddIndex(
            model_name='usersolutionaccess',
            index=models.Index(fields=['solution', '-accessed_at'], name='idx_access_solution_time'),
        ),
        migrations.AddIndex(
            model_name='usersolutionaccess',
            index=models.Index(fields=['-accessed_at'], name='idx_access_time'),
        ),
        migrations.AddIndex(
            model_name='usersolutionassignment',
            index=models.Index(fields=['user', 'is_active'], name='idx_assignment_user_active'),
        ),
        migrations.AddIndex(
            model_name='usersolutionassignment',
            index=models.Index(fields=['solution', 'is_active'], name='idx_assignment_solution_active'),
        ),
        migrations.AddIndex(
            model_name='usersolutionassignment',
            index=models.Index(fields=['assigned_by'], name='idx_assignment_assigned_by'),
        ),
        migrations.AddIndex(
            model_name='usersolutionassignment',
            index=models.Index(fields=['-assigned_at'], name='idx_assignment_assigned_at'),
        ),
    ]
