# Generated by Django 5.2.4 on 2025-09-01 17:24

import django.db.models.deletion
import infrastructure.database.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_add_database_indexes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dessuser',
            managers=[
                ('objects', infrastructure.database.managers.DESSUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del despliegue', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción del proyecto')),
                ('github_url', models.URLField(help_text='URL del repositorio GitHub')),
                ('branch', models.CharField(default='main', help_text='Rama a desplegar', max_length=100)),
                ('project_type', models.CharField(blank=True, choices=[('django', 'Django'), ('react', 'React'), ('node', 'Node.js'), ('nextjs', 'Next.js'), ('flask', 'Flask'), ('fastapi', 'FastAPI'), ('static', 'Static Site'), ('docker', 'Docker')], help_text='Tipo de proyecto (auto-detectado)', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('cloning', 'Clonando repositorio'), ('analyzing', 'Analizando proyecto'), ('building', 'Construyendo'), ('deploying', 'Desplegando'), ('running', 'En ejecución'), ('failed', 'Falló'), ('stopped', 'Detenido')], default='pending', max_length=20)),
                ('deploy_url', models.URLField(blank=True, help_text='URL donde está desplegado')),
                ('port', models.IntegerField(blank=True, help_text='Puerto asignado', null=True)),
                ('dockerfile_path', models.CharField(default='Dockerfile', help_text='Ruta al Dockerfile', max_length=255)),
                ('build_command', models.TextField(blank=True, help_text='Comando de construcción personalizado')),
                ('start_command', models.TextField(blank=True, help_text='Comando de inicio personalizado')),
                ('environment_vars', models.JSONField(default=dict, help_text='Variables de entorno para el despliegue')),
                ('container_id', models.CharField(blank=True, max_length=255)),
                ('image_name', models.CharField(blank=True, max_length=255)),
                ('build_logs', models.TextField(blank=True)),
                ('deploy_logs', models.TextField(blank=True)),
                ('error_logs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_deployed', models.DateTimeField(blank=True, null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret para webhook', max_length=255)),
                ('auto_deploy', models.BooleanField(default=False, help_text='Auto-desplegar en push')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despliegue',
                'verbose_name_plural': 'Despliegues',
                'db_table': 'dess_deployments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='database.deployment')),
            ],
            options={
                'db_table': 'dess_deployment_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('triggered_deployment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='database.deployment')),
            ],
            options={
                'db_table': 'dess_webhook_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
