# Generated by Django 4.2 on 2025-09-08 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0004_alter_dessuser_managers_deployment_deploymentlog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFavoriteSolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="database.solution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_solutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solución Favorita",
                "verbose_name_plural": "Soluciones Favoritas",
                "db_table": "dess_user_favorite_solutions",
            },
        ),
        migrations.AddIndex(
            model_name="userfavoritesolution",
            index=models.Index(
                fields=["user", "-added_at"], name="idx_favorite_user_time"
            ),
        ),
        migrations.AddIndex(
            model_name="userfavoritesolution",
            index=models.Index(fields=["solution"], name="idx_favorite_solution"),
        ),
        migrations.AlterUniqueTogether(
            name="userfavoritesolution",
            unique_together={("user", "solution")},
        ),
    ]
